### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by rchl** [rez0n/actions-github-release#22]
It doesn't feel like it's working:

```yaml
      - name: Get latest release of rust-analyzer
        uses: rez0n/actions-github-release@v2.0
        id: latest_ra
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'rust-lang/rust-analyzer'
          type: stable
```

I'm getting:

```
  File "/entrypoint.py", line 13, in <module>
    repo = G.get_repo(repository)
  File "/usr/local/lib/python3.10/site-packages/github/MainClass.py", line 375, in get_repo
    assert isinstance(full_name_or_id, (str, int)), full_name_or_id
AssertionError: None
```

So it looks like the "repository" input is not actually passed to the python script.

According to [github documentation](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action?learn=create_actions&learnProduct=actions#creating-an-action-metadata-file) it appears that it's necessary to pass inputs as `args` in `action.yml` but I don't see that being done [here](https://github.com/rez0n/actions-github-release/blob/794c12f5e8d629e6ca329cf2e2daeb0f0ce6a3ce/action.yaml#L28-L30).
